### ISSUE TITLE
Externalize Cassandra Keyspace configuration

### ISSUE THREAD

**Issue by tnine** [tjake/Solandra#24]
We're running several processes that connect to different keyspaces in a single virtual machine.  With the current keyspace definition within the CassandraUtils as a static string, it is impossible for Readers and Writers to connect to different keyspaces, even though different Thrift api connections can be passed during instantiation.

**Comment by tjake** [comment]
Why do you need multiple keyspaces? You can have any number of indexes within a keyspace.

**Comment by tnine** [comment]
I'm connecting to two different clusters from the same VM.  One cluster used the Keyspace "Spidertracks" to hold all the secondary indexing I'm building for my Cassandra plugin.  I'm connecting to another cluster with the keyspace "GeoData".  Since I'm connecting to 2 separate clusters, I have 2 different keyspaces I need to connect to.

**Comment by tjake** [comment]
I need keyspace to be a static global parameter, I could add a static method to alter the keyspace at runtime, but it would be upto you to be sure this is safe for your application.  Does this work for you?

**Comment by tjake** [comment]
Done

**Comment by tnine** [comment]
Hey Jake,
  Unfortunately this fix won't work for me.  You have configured it as a system property, which doesn't resolve my use case above.  I'm in 1 JVM, and connecting to 2 separate index keyspaces.  Check out my fork, I pass in a context for each reader and writer that allows it to connect to the key space I need.  I've been steadily merging in your changes, so you should be a able to pull my fork into a branch with your current code base and the context added as well.
